### ISSUE TITLE
Upgrade to Vyper 0.1.0b11

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#43]
And use` @nonreentrant('lock')` decorator for `addLiquidity`, `removeLiquidity` and `swapTokens`

**Comment by blimp666** [comment]
After an upgrade to 0.1.0b11 we will not be able to verify the contract at etherscan (it supports vyper only up to b9 version). Is it ok?

**Comment by gonchs** [comment]
Ah yes, that was the reason. I remember now. Stay at b9.

**Comment by blimp666** [comment]
Newer Vyper versions up to 0.1.0b12 were recently added at etherscan.io

**Comment by gonchs** [comment]
I've also noticed today. I tried upgrading but the tests started failing.
I'm not sure there is much benefit in upgrading to justify the additional
development time. What do you think could be the benefits?

**Comment by blimp666** [comment]
Yes, you're right, now I see that tests are red with b12 - it fails with ```Cannot call public functions via 'self'``` (due to this change https://github.com/ethereum/vyper/commit/b1c79556d5906f73a6c687925a5b6dd60db96f31 as a part of https://github.com/ethereum/vyper/issues/1199 ). However tests are green with b11, b11 includes performance and stability fixes, and I think it would be useful to upgrade at least to b11.

As for b12, there are some bugfixes too, but it seems now we can't call public methods internally.  As far as I understand it, if we want to use b12, we just should have private methods (like ```tokenExchangeRateAfterFees```) and public wrappers to them. It should not affect a transaction cost, however it will increase a contract size a bit.

**Comment by gonchs** [comment]
Can you upgrade to b11 and add `@nonreentrant('lock')` decorator to `addLiquidity`, `removeLiquidity` and `swapTokens` ?
