### ISSUE TITLE
Optimize gas usage

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#45]
Optimize `tokenExchangeRateAfterFees`, `tokenOutputAmountAfterFees` and `swapTokens` gas usage and (if possible) increase the precision for low-decimal tokens.

**Comment by blimp666** [comment]
Just an idea: in  ```tokenExchangeRateAfterFees``` we have ```10 ** ERC20(input_token_address).decimals()``` as a multiplier. The reason was described at https://github.com/stablecoinswap/stablecoinswap-contracts/pull/42#issuecomment-524704476 , it gives us necessary presicion . But It seems we could use here just a large constant (```10 ** 18``` or maybe even ```TOKEN_PRICE_MULTIPLIER``` would be enough). And then use the same constant in ```tokenOutputAmountAfterFees```.  
It will remove two external calls and save some gas.

**Comment by gonchs** [comment]
@blimp666 please self-assign https://github.com/stablecoinswap/docs/issues/1
