### ISSUE TITLE
Proxy contract to charge extra fees

### ISSUE THREAD

**Issue by gonchs** [stablecoinswap/stablecoinswap-contracts#54]
Related to the Kyber integration. Kyber requires us to pay 0.25% on all trades. To compensate for this, we need to charge this extra fee on all trades from Kyber.

Create a proxy contract which will take the same arguments for the swap function and pass them into the main contract. But it would then also charge an extra 0.25% fee kept in the contract balance.

Owner should be able to withdraw these fees.

Ownership should be transferrable.

Fee should be changeable by the owner.

Contract should have the same pricing functions to get the expected conversation rate and out amount. They should include the extra fee.

There should not be any erc20, liquidity-related or permission-related functions. This contract is purely for collection fees from the Kyber-originated swaps.

The idea is that from time to time, we'll withdraw this extra fee to pay Kyber for the trades.

**Comment by blimp666** [comment]
So, if user wants to swap USDC to PAX (both have price 1.00 USD with a current fixed_price_oracle), then he will have to pay 0.25% more USDC if he's using proxy, correct?
 
For example, if total fees of stablecoinswap contract are 0.3%, then user can swap 100 USDC to 99.7 PAX (when interacts stablecoinswap contract directly). tokenExchangeRateAfterFees in stablecoinswap contract will return  9970000000000000000000 (0.997 * EXCHANGE_RATE_MULTIPLIER) for this pair.

But if he's using the proxy contract, then he has to pay 100.25 USDC to get the same amount of PAX (99.7 PAX). So, he will call ```proxy.swapTokens(input: 100.25 USDC, min_output: 99.7 PAX)```, the proxy contract will call stablecoinswap.swapTokens(input: 100 USDC, output: min 99.7 PAX), and also will transfer 0.25 USDC from the user to itself. tokenExchangeRateAfterFees in the proxy contract should return 99451371571072319201 (0.997/1.0025 * EXCHANGE_RATE_MULTIPLIER). 

Am I right?

And one more question: should it be 0.25% of the value passed into original stablecoinswap contract (as it described in my example above), or 0.25% of the value passed into the proxy contract?

Also if I understood this correctly, it seems in this scenario a user have to approve USDC transfers for both contracts (proxy and main stablecoinswap), because both of them will do transfers.

**Comment by gonchs** [comment]
The answer depends on how Ethereum treats msg.sender.

If the sender inside of the main contract is the proxy contract, funds will be transferred into the proxy and we need to resend them to the user. And we will take the fee out of these funds (send the user less than what we got back from the main contract).

If the sender is the user, then it should be as you described.

Fee can be taken out of input or output funds, whichever is easier to implement or consumes significantly less gas.

I imagine the user would enter the amount on Kyber of 100 DAI into USDC, Kyber would look who gives the highest output of USDC and use them. So our proxy may first take the input of 100 DAI and return and expected output. And if Kyber decides to use us, then it will pass 100 DAI as an argument I to the swap function with the min amount set to whatever the pricing function before returned.

**Comment by blimp666** [comment]
You're right, msg.sender inside of the main contract will be the proxy contract. So we need multiple transfers here: transfer input tokens from the user into the proxy, then swap in the main contract, and then transfer output tokens from the proxy to the user.

**Comment by blimp666** [comment]
How should we round fees in the proxy? Should we round it up (ceil)? So if user swaps 5 GUSD, the proxy contract will charge him by 0.02 GUSD (0.25% of 5 GUSD is 0.0125, but GUSD has 2 decimals only).

**Comment by gonchs** [comment]
Yes, please round up.
